SET DATEFORMAT YMD


/************ ENCABEZADO ***************/

--------------TABLA 
CREATE TABLE SJ_DAFITI_API_ENCABEZADO
(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
ORDER_ID INT,
ORDER_NUMBER INT,
FECHA_INGRESO DATETIME DEFAULT GETDATE(),
FECHA_CREATE DATETIME,
CANT_ART INT,
PRICE FLOAT
)

GO
--------------SP
CREATE PROCEDURE SJ_DAFITI_API_INSERT_ENCABEZADO
(
@ORDER_ID INT,
@ORDER_NUMBER INT,
@FECHA_CREATE DATETIME,
@CANT_ART INT,
@PRICE FLOAT
)
AS
BEGIN

INSERT INTO SJ_DAFITI_API_ENCABEZADO (ORDER_ID, ORDER_NUMBER, FECHA_CREATE, CANT_ART, PRICE)
VALUES (@ORDER_ID, @ORDER_NUMBER, @FECHA_CREATE, @CANT_ART, @PRICE)

END



/************ DETALLE ***************/

--------------TABLA 

CREATE TABLE SJ_DAFITI_API_DETALLE
(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
ORDER_ID INT,
ORDER_NUMBER INT,
FECHA_INGRESO DATETIME DEFAULT GETDATE(),
FECHA_CREATE DATETIME,
NRO_ART INT,
COD_ARTICU VARCHAR(20),
PRECIO_ART FLOAT
)

GO

--------------SP
CREATE PROCEDURE SJ_DAFITI_API_INSERT_DETALLE
(
@ORDER_ID INT,
@ORDER_NUMBER INT,
@FECHA_CREATE DATETIME,
@NRO_ART INT,
@COD_ARTICU VARCHAR(20),
@PRICE_ART FLOAT
)
AS
BEGIN

INSERT INTO SJ_DAFITI_API_DETALLE (ORDER_ID, ORDER_NUMBER, FECHA_CREATE, NRO_ART, COD_ARTICU, PRECIO_ART)
VALUES (@ORDER_ID, @ORDER_NUMBER, @FECHA_CREATE, @NRO_ART, @COD_ARTICU, @PRICE_ART)

END


/************ CLIENTE ***************/

--------------TABLA 

CREATE TABLE SJ_DAFITI_API_CLIENTE
(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
ORDER_ID INT,
ORDER_NUMBER INT,
FECHA_INGRESO DATETIME DEFAULT GETDATE(),
FECHA_CREATE DATETIME,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30),
TELEFONO_1 VARCHAR(25),
TELEFONO_2 VARCHAR(25),
DIRECCION_1 VARCHAR(70),
DIRECCION_2 VARCHAR(70),
CIUDAD VARCHAR(50),
C_POSTAL VARCHAR(10),
E_MAIL VARCHAR(50),
DNI VARCHAR(20)
)

GO
--------------SP

ALTER PROCEDURE SJ_DAFITI_API_INSERT_CLIENTE
(
@ORDER_ID INT,
@ORDER_NUMBER INT,
@FECHA_CREATE DATETIME,
@FIRST_NAME VARCHAR(30),
@LAST_NAME VARCHAR(30),
@TELEFONO_1 VARCHAR(25),
@TELEFONO_2 VARCHAR(25),
@DIRECCION_1 VARCHAR(70),
@DIRECCION_2 VARCHAR(70),
@CIUDAD VARCHAR(50),
@C_POSTAL VARCHAR(10),
@E_MAIL VARCHAR(50),
@DNI VARCHAR(20)
)
AS
BEGIN
INSERT INTO SJ_DAFITI_API_CLIENTE (ORDER_ID, ORDER_NUMBER, FECHA_CREATE, FIRST_NAME, LAST_NAME, TELEFONO_1, TELEFONO_2, DIRECCION_1, DIRECCION_2, CIUDAD, C_POSTAL, E_MAIL, DNI) 
VALUES (@ORDER_ID, @ORDER_NUMBER, @FECHA_CREATE, @FIRST_NAME, @LAST_NAME, @TELEFONO_1, @TELEFONO_2, @DIRECCION_1, @DIRECCION_2, @CIUDAD, @C_POSTAL, @E_MAIL, @DNI)
END

GO


SELECT * FROM SOF_AUDITORIA WHERE NRO_ORDEN_ECOMMERCE = '229341672'

/**********************************************/


SELECT * FROM SJ_DAFITI_API_ENCABEZADO --26
SELECT * FROM SJ_DAFITI_API_DETALLE 
SELECT * FROM SJ_DAFITI_API_CLIENTE



SELECT * FROM GVA21 WHERE FECHA_PEDI >= '2020-11-11' AND LEYENDA_3 = 'API-DAFITI CARGADO DESDE APP ECOMMERCE'
SELECT * FROM GVA03 WHERE NRO_PEDIDO IN ( SELECT NRO_PEDIDO FROM GVA21 WHERE FECHA_PEDI >= '2020-11-11' AND LEYENDA_3 = 'API-DAFITI CARGADO DESDE APP ECOMMERCE' )
SELECT * FROM GVA38 WHERE T_COMP = 'PED' AND N_COMP IN ( SELECT NRO_PEDIDO  FROM GVA21 WHERE FECHA_PEDI >= '2020-11-11' AND LEYENDA_3 = 'API-DAFITI CARGADO DESDE APP ECOMMERCE')
SELECT * FROM SOF_AUDITORIA WHERE FECHA_PEDIDO >= '2020-11-11' AND ORIGEN = 'DAA'


/*

--LIMPIAR LOS QUE NO ENTRAN EN ARTICULOS

SELECT COUNT(*) FROM SJ_DAFITI_API_ENCABEZADO WHERE ORDER_NUMBER NOT IN (SELECT ORDER_NUMBER FROM SJ_DAFITI_API_DETALLE)
SELECT COUNT(*) FROM SJ_DAFITI_API_CLIENTE WHERE ORDER_NUMBER NOT IN (SELECT ORDER_NUMBER FROM SJ_DAFITI_API_DETALLE)
SELECT COUNT(*) FROM GVA21 WHERE FECHA_PEDI >= '2020-11-11' AND LEYENDA_3 = 'API-DAFITI CARGADO DESDE APP ECOMMERCE' AND NRO_PEDIDO NOT IN (SELECT DISTINCT NRO_PEDIDO FROM GVA03)
SELECT COUNT(*) FROM GVA38 WHERE T_COMP = 'PED' AND TALONARIO = 101 AND N_COMP NOT IN ( SELECT DISTINCT NRO_PEDIDO FROM GVA03)
SELECT COUNT(*) FROM SOF_AUDITORIA WHERE FECHA_PEDIDO >= '2020-11-11' AND ORIGEN = 'DAA' AND NRO_ORDEN_ECOMMERCE NOT IN (SELECT ORDER_NUMBER FROM SJ_DAFITI_API_DETALLE)


DELETE FROM SJ_DAFITI_API_ENCABEZADO WHERE ORDER_NUMBER NOT IN (SELECT ORDER_NUMBER FROM SJ_DAFITI_API_DETALLE)
DELETE FROM SJ_DAFITI_API_CLIENTE WHERE ORDER_NUMBER NOT IN (SELECT ORDER_NUMBER FROM SJ_DAFITI_API_DETALLE)
DELETE FROM GVA21 WHERE FECHA_PEDI >= '2020-11-11' AND LEYENDA_3 = 'API-DAFITI CARGADO DESDE APP ECOMMERCE' AND NRO_PEDIDO NOT IN (SELECT DISTINCT NRO_PEDIDO FROM GVA03)
DELETE FROM GVA38 WHERE T_COMP = 'PED' AND TALONARIO = 101 AND N_COMP NOT IN ( SELECT DISTINCT NRO_PEDIDO FROM GVA03)
DELETE FROM SOF_AUDITORIA WHERE FECHA_PEDIDO >= '2020-11-11' AND ORIGEN = 'DAA' AND NRO_ORDEN_ECOMMERCE NOT IN (SELECT ORDER_NUMBER FROM SJ_DAFITI_API_DETALLE)

SELECT * 
--DELETE
FROM GVA21 
WHERE LEYENDA_3 = 'API-DAFITI CARGADO DESDE APP ECOMMERCE' 
AND TALON_PED = 101 
AND NRO_PEDIDO NOT IN (SELECT DISTINCT NRO_PEDIDO FROM GVA03 WHERE TALON_PED = 101 AND NRO_PEDIDO LIKE ' 0000200%')

SELECT * 
--DELETE
FROM GVA03
WHERE TALON_PED = 101 AND NRO_PEDIDO LIKE ' 0000200%'
AND NRO_PEDIDO NOT IN (SELECT NRO_PEDIDO FROM GVA21 WHERE TALON_PED = 101 )

SELECT * 
--DELETE
FROM SOF_AUDITORIA 
WHERE ORIGEN = 'DAA' 
AND FECHA_PEDIDO = '2020-12-22'
AND NRO_PEDIDO NOT IN (SELECT NRO_PEDIDO FROM GVA21 WHERE TALON_PED = 101)


*/


SELECT A.CANT_ART, A.PRICE, C.NRO_PEDIDO, D.*, E.COD_ARTICU FROM SJ_DAFITI_API_ENCABEZADO A
INNER JOIN SJ_DAFITI_API_CLIENTE B
ON A.ORDER_ID = B.ORDER_ID AND A.ORDER_NUMBER = B.ORDER_NUMBER
INNER JOIN SOF_AUDITORIA C
ON CAST(A.ORDER_NUMBER AS VARCHAR) COLLATE Latin1_General_BIN  = C.NRO_ORDEN_ECOMMERCE
LEFT JOIN SJ_DAFITI_API_DETALLE D
ON A.ORDER_ID = D.ORDER_ID AND A.ORDER_NUMBER = D.ORDER_NUMBER
LEFT JOIN GVA03 E
ON C.NRO_PEDIDO = E.NRO_PEDIDO


SELECT A.CANT_ART, A.PRICE, B.* FROM SJ_DAFITI_API_ENCABEZADO A
	INNER JOIN SJ_DAFITI_API_CLIENTE B
	ON A.ORDER_ID = B.ORDER_ID AND A.ORDER_NUMBER = B.ORDER_NUMBER
	WHERE CAST(A.ORDER_NUMBER AS VARCHAR) COLLATE Latin1_General_BIN NOT IN 
	(SELECT NRO_ORDEN_ECOMMERCE FROM SOF_AUDITORIA)	




SELECT * 
DELETE
FROM SJ_DAFITI_API_ENCABEZADO 
WHERE ORDER_NUMBER NOT IN
--INNER JOIN 
(
	SELECT DISTINCT A.ID_EXTERNO FROM GVA21 A 
	INNER JOIN GVA03 B ON A.TALON_PED = B.TALON_PED AND A.NRO_PEDIDO = B.NRO_PEDIDO 
	WHERE A.TALON_PED = 101 and A.LEYENDA_3 LIKE 'API-DAFITI%'
) B
ON A.ORDER_NUMBER = B.ID_EXTERNO


SELECT * 
--DELETE
FROM GVA21 WHERE TALON_PED = 101 and LEYENDA_3 LIKE 'API-DAFITI%'
AND NRO_PEDIDO NOT IN (SELECT DISTINCT NRO_PEDIDO FROM GVA03 WHERE TALON_PED = 101)


SELECT * 
--DELETE
FROM GVA38 WHERE TALONARIO = 101 --and a.LEYENDA_3 LIKE 'API-DAFITI%'
AND N_COMP NOT IN (SELECT DISTINCT NRO_PEDIDO FROM GVA03 WHERE TALON_PED = 101)
ORDER BY RAZON_SOCI


/*
DELETE FROM GVA03 WHERE NRO_PEDIDO IN ( SELECT NRO_PEDIDO FROM GVA21 WHERE FECHA_PEDI = '2020-11-09' AND LEYENDA_3 = 'API-DAFITI CARGADO DESDE APP ECOMMERCE')
DELETE FROM GVA38 WHERE T_COMP = 'PED' AND N_COMP IN ( SELECT NRO_PEDIDO FROM GVA21 WHERE FECHA_PEDI = '2020-11-09' AND LEYENDA_3 = 'API-DAFITI CARGADO DESDE APP ECOMMERCE')
DELETE FROM SOF_AUDITORIA WHERE FECHA_PEDIDO = '2020-11-09' AND ORIGEN = 'DAA'
DELETE FROM GVA21 WHERE FECHA_PEDI = '2020-11-09' AND LEYENDA_3 = 'API-DAFITI CARGADO DESDE APP ECOMMERCE'
*/

/*
TRUNCAT E TABLE SJ_DAFITI_API_ENCABEZADO
TRUNCAT E TABLE SJ_DAFITI_API_CLIENTE
TRUNCAT E TABLE SJ_DAFITI_API_DETALLE
*/

SELECT 
'DAF', ORDER_NUMBER, '$numPedido', CAST(GETDATE() AS date), '$cliente', A.COD_ARTICU, LEFT(B.DESCRIPCIO, 30), 1, PRECIO_ART, 'Pay U', PRECIO_ART, 'Pay U', NULL, 0, NULL, NULL
FROM 
(
SELECT A.CANT_ART, A.PRICE, B.*, C.COD_ARTICU, C.PRECIO_ART FROM SJ_DAFITI_API_ENCABEZADO A 
INNER JOIN SJ_DAFITI_API_CLIENTE B 
ON A.ORDER_ID = B.ORDER_ID AND A.ORDER_NUMBER = B.ORDER_NUMBER
INNER JOIN SJ_DAFITI_API_DETALLE C
ON A.ORDER_ID = C.ORDER_ID AND A.ORDER_NUMBER = C.ORDER_NUMBER
) A
INNER JOIN STA11 B
ON A.COD_ARTICU collate Latin1_General_BIN = B.COD_ARTICU

WHERE CAST(ORDER_NUMBER AS VARCHAR) collate Latin1_General_BIN
NOT IN (SELECT NRO_ORDEN_ECOMMERCE FROM SOF_AUDITORIA)
AND CAST(ORDER_NUMBER AS VARCHAR) collate Latin1_General_BIN = '$ordenEcommerce'




SELECT * FROM SJ_DAFITI_API_DETALLE WHERE CAST(ORDER_NUMBER AS VARCHAR) COLLATE Latin1_General_BIN = '256182272'


SET DATEFORMAT YMD

	SELECT A.CANT_ART, A.PRICE, B.* FROM SJ_DAFITI_API_ENCABEZADO A
	INNER JOIN SJ_DAFITI_API_CLIENTE B
	ON A.ORDER_ID = B.ORDER_ID AND A.ORDER_NUMBER = B.ORDER_NUMBER
	WHERE CAST(A.ORDER_ID AS VARCHAR) COLLATE Latin1_General_BIN NOT IN 
	(SELECT NRO_ORDEN_ECOMMERCE FROM SOF_AUDITORIA)	

SELECT REPLACE(NRO_ORDEN_ECOMMERCE, '_', ''), * 
--UPDATE SOF_AUDITORIA SET NRO_ORDEN_ECOMMERCE = REPLACE(NRO_ORDEN_ECOMMERCE, '_', '')
FROM SOF_AUDITORIA WHERE ORIGEN = 'DAF' AND FECHA_PEDIDO >= GETDATE()-15 AND NRO_ORDEN_ECOMMERCE LIKE '%[_]'
